/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/simulate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulate */
        get: operations["get_simulate_simulate__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/predict/{crop_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Yield Prediction */
        post: operations["get_yield_prediction_simulate_predict__crop_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/optimise/{crop_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Optimised Levels */
        post: operations["get_optimised_levels_simulate_optimise__crop_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/graph/{crop_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Graph */
        post: operations["get_graph_simulate_graph__crop_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate/llm/{crop_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Optimised Levels */
        post: operations["get_optimised_levels_simulate_llm__crop_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data */
        get: operations["get_data_data__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Graph Data */
        post: operations["get_graph_data_data_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Llm Advice */
        post: operations["get_llm_advice_data_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_get_graph_data_data_results_post */
        Body_get_graph_data_data_results_post: {
            /** File */
            file: string;
            /** Forecast Day Num */
            forecast_day_num: number;
        };
        /** Body_get_llm_advice_data_llm_post */
        Body_get_llm_advice_data_llm_post: {
            /** Crop */
            crop: string;
            /** File */
            file: string;
        };
        /** ComparisonGraphResponse */
        ComparisonGraphResponse: {
            /**
             * Crop
             * @enum {string}
             */
            crop: "cucumber" | "tomato";
            /** Optimal Array */
            optimal_array: [
                number,
                number
            ][];
            /** Current Array */
            current_array: [
                number,
                number
            ][];
            /** Domain */
            domain: number;
            /** Max Growth */
            max_growth: number;
        };
        /** ConstrainedSensorData */
        ConstrainedSensorData: {
            /** Avg Ph */
            Avg_pH?: number | null;
            /** Avg Ec */
            Avg_EC?: number | null;
            /** Avg Co2 */
            Avg_CO2?: number | null;
            /** Avg Rh */
            Avg_RH?: number | null;
            /** Avg Air Temp */
            Avg_Air_Temp?: number | null;
            /** Avg Water Temp */
            Avg_Water_Temp?: number | null;
            /** Avg Tds */
            Avg_TDS?: number | null;
            /** Avg Dli */
            Avg_DLI?: number | null;
        };
        /** CucumberSensorData */
        CucumberSensorData: {
            /** Avg Ph */
            Avg_pH: number;
            /** Avg Ec */
            Avg_EC: number;
            /** Avg Co2 */
            Avg_CO2: number;
            /** Avg Rh */
            Avg_RH: number;
            /** Avg Air Temp */
            Avg_Air_Temp: number;
            /** Avg Dli */
            Avg_DLI: number;
        };
        /** CucumberSensorDataRequest */
        CucumberSensorDataRequest: {
            /** Avg Ph */
            Avg_pH: number;
            /** Avg Ec */
            Avg_EC: number;
            /** Avg Co2 */
            Avg_CO2: number;
            /** Avg Rh */
            Avg_RH: number;
            /** Avg Air Temp */
            Avg_Air_Temp: number;
            /** Avg Dli */
            Avg_DLI: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            crop: "cucumber";
        };
        /** GraphResults */
        GraphResults: {
            /** Optimal Array */
            optimal_array: [
                number,
                number
            ][];
            /** Current Array */
            current_array: [
                number,
                number
            ][];
            /** Domain */
            domain: number;
            /** Max Growth */
            max_growth: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HydroponicAdvice */
        HydroponicAdvice: {
            /**
             * Status
             * @description Health assessment: Optimal, Suboptimal, or Critical
             */
            status: string;
            /**
             * Advice Summary
             * @description 1-sentence summary of the situation
             */
            advice_summary: string;
            /**
             * Action Steps
             * @description Specific steps to take
             */
            action_steps: string[];
            /**
             * Priority Score
             * @description Urgency from 1 to 10
             */
            priority_score: number;
        };
        /** LLMRequest */
        LLMRequest: {
            /** Sensor Data */
            sensor_data: components["schemas"]["LettuceSensorDataRequest"] | components["schemas"]["TomatoSensorDataRequest"] | components["schemas"]["CucumberSensorDataRequest"];
            constrained_sensor_data: components["schemas"]["ConstrainedSensorData"];
            /** Optimal Environment */
            optimal_environment?: {
                [key: string]: number;
            } | null;
        };
        /** LettuceGraphResponse */
        LettuceGraphResponse: {
            /**
             * Crop
             * @constant
             */
            crop: "lettuce";
            /** Baseline Curve */
            baseline_curve: [
                number,
                number
            ][];
            /** Optimised Curve */
            optimised_curve: [
                number,
                number
            ][];
        };
        /** LettuceSensorData */
        LettuceSensorData: {
            /** Avg Ph */
            Avg_pH: number;
            /** Avg Ec */
            Avg_EC: number;
            /** Avg Co2 */
            Avg_CO2: number;
            /** Avg Rh */
            Avg_RH: number;
            /** Avg Air Temp */
            Avg_Air_Temp: number;
            /** Avg Water Temp */
            Avg_Water_Temp: number;
            /** Avg Tds */
            Avg_TDS: number;
        };
        /** LettuceSensorDataRequest */
        LettuceSensorDataRequest: {
            /** Avg Ph */
            Avg_pH: number;
            /** Avg Ec */
            Avg_EC: number;
            /** Avg Co2 */
            Avg_CO2: number;
            /** Avg Rh */
            Avg_RH: number;
            /** Avg Air Temp */
            Avg_Air_Temp: number;
            /** Avg Water Temp */
            Avg_Water_Temp: number;
            /** Avg Tds */
            Avg_TDS: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            crop: "lettuce";
        };
        /** OptimisationData */
        OptimisationData: {
            /** Crop */
            crop: string;
            /** Optimal Environment */
            optimal_environment: components["schemas"]["LettuceSensorData"] | components["schemas"]["TomatoSensorData"] | components["schemas"]["CucumberSensorData"];
            /** Optimal Yield */
            optimal_yield: number;
        };
        /** PredictionData */
        PredictionData: {
            /** Crop */
            crop: string;
            /** Harvest Weight */
            harvest_weight: number;
        };
        /** TomatoSensorData */
        TomatoSensorData: {
            /** Avg Ph */
            Avg_pH: number;
            /** Avg Ec */
            Avg_EC: number;
            /** Avg Co2 */
            Avg_CO2: number;
            /** Avg Rh */
            Avg_RH: number;
            /** Avg Air Temp */
            Avg_Air_Temp: number;
            /** Avg Dli */
            Avg_DLI: number;
        };
        /** TomatoSensorDataRequest */
        TomatoSensorDataRequest: {
            /** Avg Ph */
            Avg_pH: number;
            /** Avg Ec */
            Avg_EC: number;
            /** Avg Co2 */
            Avg_CO2: number;
            /** Avg Rh */
            Avg_RH: number;
            /** Avg Air Temp */
            Avg_Air_Temp: number;
            /** Avg Dli */
            Avg_DLI: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            crop: "tomato";
        };
        /** UserDataAdvice */
        UserDataAdvice: {
            /**
             * Most Influential Feature
             * @description 1 sentence summary of the most influential features and their impact direction
             */
            most_influential_feature: string;
            /**
             * Strongest Feature
             * @description The single most influential feature and its impact direction, along with an example of how it affects growth
             */
            strongest_feature: string;
            /**
             * Advice Per Feature
             * @description Specific advice for each influential feature
             */
            advice_per_feature: string[];
            /**
             * General Advice
             * @description Overall advice based on the feature importance analysis
             */
            general_advice: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_simulate_simulate__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_yield_prediction_simulate_predict__crop_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crop_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LettuceSensorDataRequest"] | components["schemas"]["TomatoSensorDataRequest"] | components["schemas"]["CucumberSensorDataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_optimised_levels_simulate_optimise__crop_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crop_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstrainedSensorData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimisationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_simulate_graph__crop_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crop_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LettuceSensorDataRequest"] | components["schemas"]["TomatoSensorDataRequest"] | components["schemas"]["CucumberSensorDataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LettuceGraphResponse"] | components["schemas"]["ComparisonGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_optimised_levels_simulate_llm__crop_type__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crop_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HydroponicAdvice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_data__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_graph_data_data_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_get_graph_data_data_results_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_advice_data_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_get_llm_advice_data_llm_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataAdvice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
